name: dart_cassandra_cql
version: 0.1.0
author: Achilleas Anagnostopoulos <achilleas.imap.mbox@gmail.com>
description: Dart driver for apache cassandra
homepage: https://github.com/achilleasa/dart_cassandra_cql
dependencies:
  uuid: 0.3.2
  collection: ">=0.9.3+1 <0.10.0"
  logging: ">=0.9.1+1 <0.10.0"
  unittest: ">=0.11.0+5 <0.12.0"
